/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      collapsed: false,
      type: 'category',
      label: "Overview",
      items: [
        "overview/example",
        "overview/getting_started"
      ]
    },
    {
      collapsed: false,
      type: 'category',
      label: "Schema",
      items: [
        "schema/output_types",
        "schema/input_types",
        "schema/dsl",
        "schema/resolvers",
        "schema/schema",
        "schema/context",
        "schema/error_handling",
        "schema/compiler",
        "schema/graph_philosophy",
      ]
    },
    {
      collapsed: true,
      type: 'category',
      label: "Execution",
      items: [
        "execution/planning",
        "execution/statistics",
      ]
    },
    {
      collapsed: false,
      type: 'category',
      label: "Integrations",
      items: [
        "integrations/http4s",
        "integrations/graphqlws",
        "integrations/natchez",
      ]
    }
  ]

  // But you can create a sidebar manually
  // mdoc: [
  //   {
  //     type: "autogenerated",
  //     dirName: "../modules/docs/target/mdoc"
  //     // items: ["test"],
  //   }
  // ]
    // 'intro',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  // ],
};

module.exports = sidebars;
